### ISSUE TITLE
Default behaviours for filetype and GDAL

### ISSUE THREAD

**Issue by njtierney** [njtierney/geotargets#16]
As noted at https://github.com/njtierney/geotargets/blob/master/R/tar-terra-rast.R#L66-L73 by @brownag 

It could be a good idea to have some default values for things like raster filetypes ("GTiff", "netCDF", ?) and GDAL ("ENCODING=UTF-8").

These could be set with `options` or maybe there's a way {targets} like us to set target options - `tar_option_set()` doesn't look like it has slots for new arguments, so either we make our own `geotarget_option_set` function, or we can get the user to use `options` or set an envvar, or something. Note that https://design.tidyverse.org/def-user.html doesn't discuss this in great detail.

**Comment by njtierney** [comment]
Fantastic, thank you so much! Looks great, just got some function name suggestions linked in the PR

That {covr} error was annoying, thanks for fixing that!

**Comment by Aariq** [comment]
Closed by #19
