### ISSUE TITLE
Create vignette for tar_terra_* targets use

### ISSUE THREAD

**Issue by njtierney** [njtierney/geotargets#17]
See https://github.com/ropensci-books/targets/blob/main/walkthrough.qmd and https://github.com/ropensci/stantargets/blob/main/vignettes/introduction.Rmd for details on setting up targets in a vignette

**Comment by Aariq** [comment]
Hey @njtierney, do you think you'll have time to finish up a draft of this "getting started" vignette in the next couple of weeks, or would you like me to take over this PR?

**Comment by njtierney** [comment]
If you've got some time that would be great!
