### ISSUE TITLE
Naming geotargets gdal raster options

### ISSUE THREAD

**Issue by njtierney** [njtierney/geotargets#25]
Breaking this out of #19 

Naming things is always a bit tricky, but following on from @Aariq 's suggestion on renaming some of the env vars, current thoughts are:

`GEOTARGETS_GDAL_RASTER_DRIVER_NAME` -- > `GEOTARGETS_GDAL_RASTER_DRIVER`

It's a small change but I think it's worthwhile to reduce typing where practical. On the [GDAL website they are called "Raster drivers"](https://gdal.org/drivers/raster/index.html) too, so there's that?

**Comment by brownag** [comment]
Totally agree with dropping "_NAME" from the option name, that is a great suggestion

I also agree with your point RE: "CREATION_OPTIONS" (https://github.com/njtierney/geotargets/pull/19#discussion_r1524052254).

At a minimum we need to distinguish between options used to write/create a datasource vs. those used to read them.

**Comment by njtierney** [comment]
closed in #30
