### ISSUE TITLE
consider how `tar_terra_sprc` might work in dynamic and static branching

### ISSUE THREAD

**Issue by njtierney** [njtierney/geotargets#53]
RE @Aariq 's comment in #50 

> ... what I really wish for is a way to use sprc() and terra::c() with dynamic and static branching. E.g., would the test pipeline in this PR perhaps be better done with tar_map() and a geotargets version of tarchetypes::tar_combine() like tar_combine_sprc()? Or would it be possible to create our own options for an iterate argument so one could use dynamic branching with iterate = "sprc" or iterate = "SpatRaster_layers"? I think we might have to dig more into the targets code or ask Will to answer those questions.

**Comment by Aariq** [comment]
Confirmed with Will that custom `iterate` arguments are not a possibility, but some equivalent of `tarchetypes::tar_combine()` might be warranted for static branching

**Comment by Aariq** [comment]
I'm reconsidering this and I now think `tar_terra_sprc()` does enough.  It can already be used it in its current form to collect targets.

```r
tar_terra_sprc(collection, sprc(list(upstream_target1, upstream_target2)))
```
