### ISSUE TITLE
RConsortium ISC proposal

### ISSUE THREAD

**Issue by Aariq** [njtierney/geotargets#6]
@brownag, @njtierney 

Would either of y'all be interested in writing an RConsortium ISC proposal to get funding to work on `geotargets`? Next proposal deadline is April 1.  More info here: https://www.r-consortium.org/all-projects/call-for-proposals

I've been on two ISC proposals in the past, and I think `geotargets` has a _really_ good chance of getting funding. I just talked to my boss and she's cool with me taking this project on as part of my official duties at University of Arizona, if we were to get it funded.

April 1 does not give us a whole lot of time, and I don't know how much time/effort y'all are planning on spending on this project. The next deadline is August 1 if you'd rather shoot for that (in the meantime, I'd still be interested in contributing, I just wouldn't be able to devote as much of my time without funding).

I'm happy to start a separate repo with a template for the proposal where we could continue discussion on this.  Just checking here to see who wants to be involved and when!  Maybe if we are going to shoot for April 1, we should just set up a Zoom meeting to chat?

**Comment by njtierney** [comment]
I'm keen to help write this grant! This work would be really useful for my team so I'm keen to set aside time to work on this.

Agreed that April 1 is not a lot of time, but I think we can put something together. If you're happy to start a separate repo with a template we could continue chatting there?

**Comment by Aariq** [comment]
Here's the repo, in case others want to watch or be involved: https://github.com/njtierney/geotargets
