### ISSUE TITLE
Multiple calls to `geotargets_option_set()` nulls out existing options

### ISSUE THREAD

**Issue by brownag** [njtierney/geotargets#64]
One more thing I noticed after #45 

``` r
library(geotargets)

# set an option
geotargets_option_set(gdal_raster_driver = "GPKG")

# as expected
geotargets_option_get("gdal_raster_driver")
#> [1] "GPKG"

# set a different option
geotargets_option_set(gdal_vector_driver = "GPKG")

# both should be "GPKG"
geotargets_option_get("gdal_vector_driver")
#> NULL
geotargets_option_get("gdal_raster_driver")
#> NULL
```

This way of setting options all at once is the issue, due to default NULL argument values:
https://github.com/njtierney/geotargets/blob/c148f7b9d7e8a94430133f1e978fce2d96d84110/R/geotargets-option.R#L40-L45

Note also that the wrong arguments are set for the vector options. Should use

```r
        "geotargets.gdal.vector.driver" = gdal_vector_driver,
        "geotargets.gdal.vector.creation.options" = gdal_vector_creation_options
```

**Comment by Aariq** [comment]
Thanks, I can work on this

**Comment by Aariq** [comment]
Did a blunt-force solution to this in [e1b039f](https://github.com/njtierney/geotargets/commit/e1b039f372f5f82c9cd08ac27c319c08955f0c75) which I accidentally pushed to master.  I feel like there has to be a more programmatic way to do this though, so I'll keep this open for a bit in case I think of anything or anyone has any suggestions.
