### ISSUE TITLE
`tile_n()` - as part of `tar_terra_tiling`

### ISSUE THREAD

**Issue by njtierney** [njtierney/geotargets#86]
A `tile_n` function could be specified that must be a square number, and that could then specify breaking it into n tiles. e.g., tile_n(4) would be a 2x2.

This could be useful if you know that you want to split up something into 9 pieces because you know you've got 9 cores/cpus/workers? But it might not be necessary.

Related to #83 and #84

**Comment by Aariq** [comment]
Feel free to make a PR.  I think this would be a fine addition

**Comment by Aariq** [comment]
What happens if, for example, `n = 7`?  Should we a) create 7 tiles that are unequal in size (e.g create 8 tiles and merge two of them), b) create 6 or 8 tiles and inform the user, c) error?

**Comment by Aariq** [comment]
Nevermind, we could just create tiles as rows.  So 7 tiles is 1 column and 7 rows.
